#ifndef DATA_H
#define DATA_H
#include <string>

std::string cs_yes[15] = {
	"THESE GENERALLY HAVE A LARGE CAPACITY BUT ARE SLOWER THE TIME IT TAKES TO ACCESS A CHUNK OF DATA IS LONGER",
	"DATA ANALYSIS IS A PROCESS OF INSPECTING CLEANSING TRANSFORMING AND MODELING DATA WITH THE GOAL OF DISCOVERING USEFUL INFORMATION INFORMING CONCLUSIONS AND SUPPORTING DECISION MAKING",
	"DATA ANALYSIS HAS MULTIPLE FACETS AND APPROACHES ENCOMPASSING DIVERSE TECHNIQUES UNDER A VARIETY OF NAMES AND IS USED IN DIFFERENT BUSINESS SCIENCE AND SOCIAL SCIENCE DOMAINS",
	"IN TODAYS BUSINESS WORLD DATA ANALYSIS PLAYS A ROLE IN MAKING DECISIONS MORE SCIENTIFIC AND HELPING BUSINESSES OPERATE MORE EFFECTIVELY",
	"DATA MINING IS A PARTICULAR DATA ANALYSIS TECHNIQUE THAT FOCUSES ON STATISTICAL MODELING AND KNOWLEDGE DISCOVERY FOR PREDICTIVE RATHER THAN PURELY DESCRIPTIVE PURPOSES WHILE BUSINESS INTELLIGENCE COVERS DATA ANALYSIS THAT RELIES HEAVILY ON AGGREGATION FOCUSING MAINLY ON BUSINESS INFORMATION",
	"IN STATISTICAL APPLICATIONS DATA ANALYSIS CAN BE DIVIDED INTO DESCRIPTIVE STATISTICS EXPLORATORY DATA ANALYSIS AND CONFIRMATORY DATA ANALYSIS",
	"EDA FOCUSES ON DISCOVERING NEW FEATURES IN THE DATA WHILE CDA FOCUSES ON CONFIRMING OR FALSIFYING EXISTING HYPOTHESES",
	"PREDICTIVE ANALYTICS FOCUSES ON THE APPLICATION OF STATISTICAL MODELS FOR PREDICTIVE FORECASTING OR CLASSIFICATION WHILE TEXT ANALYTICS APPLIES STATISTICAL LINGUISTIC AND STRUCTURAL TECHNIQUES TO EXTRACT AND CLASSIFY INFORMATION FROM TEXTUAL SOURCES A SPECIES OF UNSTRUCTURED DATA",
	"ALL OF THE ABOVE ARE VARIETIES OF DATA ANALYSIS",
	"ANALYSIS REFERS TO DIVIDING A WHOLE INTO ITS SEPARATE COMPONENTS FOR INDIVIDUAL EXAMINATION",
	"DATA ANALYSIS IS A PROCESS FOR OBTAINING RAW DATA AND SUBSEQUENTLY CONVERTING IT INTO INFORMATION USEFUL FOR DECISION-MAKING BY USERS",
	"DATA IS COLLECTED AND ANALYZED TO ANSWER QUESTIONS TEST HYPOTHESES OR DISPROVE THEORIES",
	"ONCE PROCESSED AND ORGANIZED THE DATA MAY BE INCOMPLETE CONTAIN DUPLICATES OR CONTAIN ERRORS",
	"THE NEED FOR DATA CLEANING WILL ARISE FROM PROBLEMS IN THE WAY THAT THE DATUM ARE ENTERED AND STORED",
	"DATA RESEARCHERS IMAGES COMPUTER ERROR KEY INFORMATION NEW PEOPLE PROGRAM DEVICES AUTOMATICALLY SOURCE SYSTEM WIRELESS REDUCE TASK MATERIALS IMAGENET SYSTEMS COMPUTATION TYPES PROCESS PRODUCE LARGE OBJECT USER LOGICAL PRACTICE HUMAN DESIGNED ALGORITHMS ENERGY NETWORK ARCHITECTURES RANDOM ELECTRONIC ELECTRICITY YEARS ACTIVE UNITED STATES SET SEASON POETRY LAND FOOD AREA WROTE WORKED WAR WALLS VOICE UKRAINIAN STEALS SMALL SINGLE SHELL SERVED SECOND SCIENTISTS RECORDED PLANT ORGANISATIONS NAME MEMBERS LIFE FILM FAMILY EVIL EQUIPMENT EPISCOPAL DEVELOPMENT DAY DAIRY CULTURAL CULTIVATED COMMUNITY BIORDERED AUSTRALIA AUDIENCE ARAB"
	
};

std::string cs_no[15] = {
	"THE MALE ADVERTISEMENT CALL IS A VERY LONG SERIES OF SINGLE NOTE CALLS LASTING UP TO TWO MINUTES",
	"WATERCOLORS HAVE BEEN EXHIBITED WIDELY IN BOTH IN THE UNITED STATES AND EUROPE AND THEY HAVE EARNED MANY PRESTIGIOUS AWARDS",
	"THE UKRAINIAN COMMUNITY IN AUSTRALIA WAS VERY ACTIVE IN THE FORMATION OF A VARIETY OF CULTURAL ORGANISATIONS INCLUDING CHOIRS FOLK DANCING GROUPS AND ARTS ORGANISATIONS LIKE THE UKRAINIAN ARTISTS SOCIETY OF AUSTRALIA",
	"SAINT MARGARET EPISCOPAL CHURCH IS STILL AN ACTIVE PARISH IN THE EPISCOPAL DIOCESE OF MARYLAND",
	"A PALETTE KNIFE IS A BLUNT TOOL USED FOR MIXING OR APPLYING PAINT WITH A FLEXIBLE STEEL BLADE",
	"BEFORE 1983 THE TITLE OF THE BEST PLAYER IN THE LEAGUE WAS SOMETIMES ASSIGNED BY A PANEL OF JOURNALISTS BUT THE CHARTS ARE INCOMPLETE",
	"THE FILM TELLS GOODMAN STORY PRIMARILY THROUGH INTERVIEWS WITH HIS CONTEMPORARIES WITH EXTENSIVE USE OF ARCHIVAL FOOTAGE AND PERSONAL PHOTOGRAPHS AS WELL AS READINGS OF HIS POETRY AND JOURNALS",
	"HE SERVED IN THE UNITED STATES NAVY FOR FOUR YEARS DURING WORLD WAR 2",
	"ADDITIONALLY SHE HAS WORKED WITH DOZENS OF NEW WRITERS HELPING DEVELOP THEIR PROJECTS",
	"THE PANTOUM IS A FORM OF POETRY SIMILAR TO A VILLANELLE IN THAT THERE ARE REPEATING LINES THROUGHOUT THE POEM",
	"AFTER 52 GAMES WITH THE AEROS DURING HIS SECOND SEASON WITHIN THE WILD ORGANIZATION IN 2012 HE WAS TRADED TO THE WASHINGTON CAPITALS IN EXCHANGE FOR A CONDITIONAL SEVENTH ROUND PICK ON MARCH 14 2013",
	"HE WROTE A DOZEN BOOKS OF POETRY FROM 1953 TO 2006 WRITING IN EPIGRAMMATIC STYLE ABOUT THINGS IN HIS EVERYDAY LIFE",
	"THE PAPER PROVIDED AN INDEPENDENT VOICE FOR THE LEFT WING ARAB TENDENCY WHICH WAS INCREASINGLY ACTIVE IN LEBANESE INTELLECTUAL AND POLITICAL LIFE IN THE YEARS AFTER THE ARAB DEFEAT IN THE SIX DAY WAR",
	"HE WAS A FULLBACK FOR THE CATHOLIC UNIVERSITY OF AMERICA AND PLAYED IN THE 1940 SUN BOWL, WHERE HE WAS DESCRIBED AS 5-FOOT 10-INCH AND 185-POUND ARIZONA JACKRABBIT",
	"MONTE BARRAU HAS A RATHER SLOPED RELIEF CHARACTERIZED BY TERTIARY CLAY DEPOSITS AND MESOZOIC CARBONATES THAT PRESENT SOMETIMES SUB VERTICAL WALLS WITH SIGNIFICANT ROCK OUTCROPS AND FREQUENT COLLAPSES"
};
#endif
